#!/usr/bin/env python3
"""Discover SpecialVInt_Array's executable entries from the pinned listing.

The generic branch-table scanner requires a label on the first BRA. This
table instead starts with RTS/NOP, followed by seven unlabeled BRA.W slots.
Export every slot, after verifying its opcode and named destination, rather
than adding individual runtime misses. No generated C is edited.
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROW = re.compile(r"^\s*\d+/\s*([0-9A-F]+)\s*:\s*(.*)$")


def discover(path, offset=0):
    labels, instructions = {}, {}
    for line in path.read_text(encoding="latin-1").splitlines():
        match = ROW.match(line)
        if not match:
            continue
        addr, text = int(match[1], 16), match[2].split(";")[0].strip()
        if re.fullmatch(r"[A-Za-z_][\w]*:", text):
            labels.setdefault(text[:-1], addr)
        emit = re.fullmatch(r"((?:[0-9A-F]{4}\s+)+)(\S.*)", text)
        if emit:
            instructions.setdefault(addr, (bytes.fromhex(emit[1]), emit[2]))
    start, end = labels["SpecialVInt_Array"], labels["SpecialVInt_VScrollOn"]
    assert end - start == 32, "SpecialVInt table shape changed"
    assert instructions[start] == (bytes.fromhex("4E75"), "rts")
    assert instructions[start + 2] == (bytes.fromhex("4E71"), "nop")
    assert any(re.fullmatch(r"jmp\s+SpecialVInt_Array\(pc,d0.w\)", src)
               for _, src in instructions.values()), "missing indexed dispatcher"
    result = [(start + offset, "SpecialVInt_Array: RTS (slot $00)")]
    for addr in range(start + 4, end, 4):
        code, src = instructions[addr]
        branch = re.fullmatch(r"bra.w\s+(SpecialVInt_\w+)", src)
        assert branch and len(code) == 4 and code[:2] == bytes.fromhex("6000"), (addr, src)
        target = addr + 2 + int.from_bytes(code[2:], "big", signed=True)
        assert target == labels[branch[1]], (addr, target, branch[1])
        result.append((addr + offset, f"{branch[1]} (slot ${addr - start:02X})"))
    return "# Generated by tools/gen_special_vint_sites.py from pinned skdisasm.\n" + \
        "# Executable RTS/NOP + BRA.W table; these are code, not pointer data.\n" + \
        "[functions]\nextra = [\n" + \
        "".join(f"    0x{addr:06X}, # {label}\n" for addr, label in result) + "]\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--sk-listing", type=Path, required=True)
    ap.add_argument("--s3-listing", type=Path, required=True)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    for mode, listing, offset in (("sandk", args.sk_listing, 0),
                                   ("sonic3k", args.sk_listing, 0),
                                   ("sonic3", args.s3_listing, 0),
                                   ("sonic3k", args.s3_listing, 0x200000)):
        part = "s3" if listing == args.s3_listing else "sk"
        path = ROOT / f"game/{mode}/{mode}.special_vint_{part}.toml"
        content = discover(listing, offset)
        if args.check:
            assert path.read_text() == content, f"discovery drift: {path}"
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
        print(path.relative_to(ROOT))


if __name__ == "__main__":
    main()
