#!/usr/bin/env python3
"""Generate Knuckles & Knuckles hook sites from the pinned S&K listing.

Every address the mod hooks is derived here from labels and instruction
patterns in skdisasm's sonic3k.lst (S&K at $000000, identical for S&K alone
and the S&K half of Sonic 3 & Knuckles):

* fixed entry points (Obj_Knuckles, Draw_Sprite, ...) by label;
* every single-character solid routine: a routine whose first instruction is
  `btst d6,status(a0)` that some object calls for Player_1 with
  p1_standing_bit (the Player_2 half of the pair is the pattern the host
  repeats for each extra);
* the Player_2 reaction that immediately follows a mirrored Player_2 call,
  keyed by the Player_1 call's return address: standing on the object
  (springs), hit from below (down springs) or touching the side (horizontal
  springs).

Outputs game/common/sonic3_knuckles_army_sites.inc and refreshes a marked
[[widescreen_site]] block in each mode's game.toml. Usage:

    tools/gen_knuckles_army_sites.py --listing <path/to/sonic3k.lst>
    tools/gen_knuckles_army_sites.py --listing <...> --check   # CI drift check
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INC = ROOT / "game/common/sonic3_knuckles_army_sites.inc"
TOMLS = [ROOT / "game/sonic3k/game.toml", ROOT / "game/sandk/game.toml"]
BEGIN = "# BEGIN knuckles-army hooks (generated by tools/gen_knuckles_army_sites.py)"
END = "# END knuckles-army hooks"
FIXED = [  # (C name, label, reason)
    ("ARMY_PC_STEP", "Obj_ResetCollisionResponseList", "Step extras after Player_2's slot"),
    ("ARMY_PC_KNUCKLES", "Obj_Knuckles", None),
    ("ARMY_PC_DPLC", "Knuckles_Load_PLC", "Extras are host-rendered: no DPLC"),
    ("ARMY_PC_DEATH", "sub_123C2", "Extra death: catch up, no life lost"),
    ("ARMY_PC_DRAW", "Draw_Sprite", "Extras never enter the SAT"),
    ("ARMY_PC_RENDER", "Render_Sprites", "Publish the crowd with the SAT"),
    ("ARMY_PC_ALLOC", "AllocateObject", "Yield a slot before allocation fails"),
    ("ARMY_PC_ALLOC_AFTER", "AllocateObjectAfterCurrent", "Yield a slot before allocation fails"),
    ("ARMY_PC_TRANSITION", "Offset_ObjectsDuringTransition", "Correct history across seamless acts"),
    ("ARMY_CODE_IDLE", "locret_13FC0", None),
    # Title gag. "@" entries resolve the first instruction matching the regex.
    ("ARMY_PC_SK_TITLE_FRAMES", r"@lea\s+\(ArtKos_SKTitle_SonKnuxHand\)\.l,a1",
     "Title gag: mirror the standing pose so Knuckles faces Knuckles"),
    ("ARMY_MAP_SK_BANNER", "Map_SKTitle_Banner", None),
    ("ARMY_MAP_AND_KNUCKLES", "Map_TitleANDKnuckles", None),
    ("ARMY_PAL_KNUCKLES", "Pal_Knuckles", None),
    ("ARMY_PC_TITLE_LOAD", "TitleSonic_LoadFrame", "Still Knuckles title: skip Sonic intro art"),
    ("ARMY_PC_TITLE_ITERATE", "Iterate_TitleSonicFrame", "Still Knuckles title: finish the Sonic intro"),
    ("ARMY_PC_TITLE_MAP", "Eni_Decomp", "Still Knuckles title: replace final Sonic plane map"),
    ("ARMY_MAP_TITLE_SONIC", "MapEni_S3TitleSonicD", None),
    ("ARMY_ART_TITLE_POSE", "ArtKosM_SonicKnuxStand", None),
    ("ARMY_ART_TITLE_POSE_END", "ArtKosM_SonicLand", None),
    ("ARMY_MAP_TITLE_POSE", "MapEni_SKTitle_Frame4", None),
    ("ARMY_MAP_TITLE_POSE_END", "MapEni_SKTitle_Background", None),
    ("ARMY_ART_TITLE_HANDS", "ArtKos_SKTitle_SonKnuxHand", None),
    ("ARMY_ART_TITLE_HANDS_END", "ArtKosM_SKTitle_Menu", None),
    ("ARMY_ART_TITLE_WORD", "ArtKosM_SKTitle_Banner", None),
    ("ARMY_ART_TITLE_WORD_END", "ArtKos_SKTitle_SonKnuxHand", None),
    ("ARMY_PAL_TITLE_KNUCKLES", "Pal_SKTitle_Knux", None),
    ("ARMY_PC_SAVE_INIT", "Obj_SaveScreen_Selector", "Knuckles mod: initialize no-save selection"),
    ("ARMY_PC_SAVE_SLOT", "loc_D41A", "Knuckles mod: initialize empty save slot selection"),
]
LINE = re.compile(r'^(?:\(\d+\))?\s*\d+/\s*([0-9A-F]+) :(?: [0-9A-F ]+)?\s{2,}(.*)$')
CALL = re.compile(r'(?:bsr|jsr)(?:\.[wsl])?\s+\(?(\w+)\)?(?:\.[wl])?$')


def load(path):
    rows = []
    for raw in open(path, encoding="latin-1"):
        m = LINE.match(raw.rstrip("\n"))
        if not m:
            continue
        text = m.group(2).split(";")[0].strip()
        if text:
            rows.append((int(m.group(1), 16), text))
    labels = {}
    for i, (_, t) in enumerate(rows):
        m = re.match(r"^([A-Za-z_.][\w.]*):(?:$|\s+ds\.)", t)
        if m and m.group(1) not in labels:
            labels[m.group(1)] = i
    return rows, labels


def discover(rows, labels):
    def ins(i):
        while i < len(rows) and rows[i][1].endswith(":"):
            i += 1
        return i

    def solid(name):
        i = labels.get(name)
        return i is not None and re.match(r"btst\s+d6,status\(a0\)$", rows[ins(i + 1)][1])

    def call_after(i, who):
        j = ins(i + 1)
        if not re.match(r"moveq\s+#%s_standing_bit,d6$" % who, rows[j][1]):
            return None
        k = ins(j + 1)
        if rows[k][1].startswith("movem.l"):
            k = ins(k + 1)
        m = CALL.match(rows[k][1])
        return (k, m.group(1)) if m and solid(m.group(1)) else None

    def following(k, n):
        out, i = [], k + 1
        while len(out) < n and i < len(rows):
            i = ins(i)
            out.append((i, rows[i][1]))
            i += 1
        return out

    def reaction(k):
        t = following(k, 12)
        text = [x[1] for x in t]
        m = CALL.match(text[2]) if len(text) > 2 else None
        if m and re.match(r"btst\s+#p2_standing_bit,status\(a0\)$", text[0]) and text[1].startswith("beq"):
            return "STANDING", m.group(1)
        if m and re.match(r"cmpi\.w\s+#-2,d4$", text[0]) and text[1].startswith("bne"):
            return "BELOW", m.group(1)
        # swap d6 / andi.w #2,d6 / beq / facing test against the object / bsr
        if len(text) > 9 and text[0] == "swap\td6" and re.match(r"andi\.w\s+#2,d6$", text[1]) \
                and re.match(r"move\.b\s+status\(a0\),d1$", text[3]) \
                and re.match(r"sub\.w\s+x_pos\(a1\),d0$", text[5]) and re.match(r"eori\.b\s+#1,d1$", text[7]):
            for _, x in t[8:]:
                m = CALL.match(x)
                if m:
                    return "SIDE", m.group(1)
        return None

    callees, sites = set(), []
    for i, (_, t) in enumerate(rows):
        if not re.match(r"lea\s+\(Player_1\)\.w,a1$", t):
            continue
        p1 = call_after(i, "p1")
        if not p1:
            continue
        k, callee = p1
        callees.add(callee)
        p2 = None
        for x in range(k + 1, min(k + 16, len(rows))):
            if re.match(r"lea\s+\(Player_2\)\.w,a1$", rows[x][1]):
                p2 = call_after(x, "p2")
                break
        react = reaction(p2[0]) if p2 and p2[1] == callee else None
        if react:
            sites.append((rows[ins(k + 1)][0], rows[labels[callee]][0], react[0], react[1]))
    return sorted(callees, key=lambda n: rows[labels[n]][0]), sites


def resolve(rows, labels, name):
    """A label's address, or with '@<regex>' the first matching instruction."""
    if name.startswith("@"):
        for a, t in rows:
            if re.match(name[1:] + "$", t):
                return a
        return None
    return rows[labels[name]][0] if name in labels else None


def pretty(label):
    """Readable form of a label or an '@' instruction pattern."""
    return re.sub(r"\\s\+", " ", label.lstrip("@")).replace("\\", "")


def render(rows, labels, callees, sites):
    def addr(name):
        return resolve(rows, labels, name)
    c = ["/* Generated by tools/gen_knuckles_army_sites.py from skdisasm sonic3k.lst. */"]
    for name, label, _ in FIXED:
        c.append("#define %-24s 0x%06Xu /* %s */" % (name, addr(label), pretty(label)))
    c.append("#ifndef ARMY_SITES_DEFINES_ONLY")
    c.append("static const uint32_t army_callees[] = {")
    c += ["    0x%06Xu, /* %s */" % (addr(n), n) for n in callees]
    c.append("};")
    c.append("static const ArmySite army_sites[] = {")
    for ret, callee, kind, target in sites:
        c.append("    { 0x%06Xu, 0x%06Xu, 0x%06Xu, REACT_%s }, /* %s */" % (callee, ret, addr(target), kind, target))
    c.append("};")
    c.append("#endif")
    t = [BEGIN]
    for _, label, why in FIXED:
        if why:
            where = "at %s" % pretty(label) if label.startswith("@") else label
            t += ["[[widescreen_site]]", "addr = 0x%X # %s (%s)" % (addr(label), why, where), 'kind = "game_hook"', ""]
    for n in callees:
        t += ["[[widescreen_site]]", "addr = 0x%X # Extras collide with %s" % (addr(n), n), 'kind = "game_hook"', ""]
    t.append(END)
    return "\n".join(c) + "\n", t


def merge_toml(text, block):
    existing = set(int(a, 16) for a in re.findall(r"^addr\s*=\s*0x([0-9A-Fa-f]+)", text.split(BEGIN)[0], re.M))
    lines, keep = [], []
    i = 0
    while i < len(block):
        if block[i] == "[[widescreen_site]]":
            a = int(re.match(r"addr = 0x([0-9A-F]+)", block[i + 1]).group(1), 16)
            if a not in existing:  # a site already declared (e.g. Render_Sprites) is shared
                keep += block[i:i + 4]
            i += 4
        else:
            keep.append(block[i])
            i += 1
    body = "\n".join(keep) + "\n"
    if BEGIN in text:
        head, rest = text.split(BEGIN, 1)
        return head + body + rest.split(END, 1)[1].lstrip("\n")
    return text.rstrip("\n") + "\n\n" + body


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--listing", type=Path, required=True)
    ap.add_argument("--check", action="store_true", help="fail if committed outputs are stale")
    args = ap.parse_args()
    rows, labels = load(args.listing)
    missing = [label for _, label, _ in FIXED if resolve(rows, labels, label) is None]
    if missing:
        sys.exit("labels missing from listing: " + ", ".join(missing))
    callees, sites = discover(rows, labels)
    if len(callees) < 20:
        sys.exit("unexpectedly few solid routines (%d)" % len(callees))
    inc, block = render(rows, labels, callees, sites)
    outputs, eol = {INC: inc}, {INC: "\n"}
    for path in TOMLS:
        raw = path.read_bytes()
        eol[path] = "\r\n" if b"\r\n" in raw else "\n"
        outputs[path] = merge_toml(raw.decode("utf-8").replace("\r\n", "\n"), block)
    def current(p):
        return p.read_bytes().decode("utf-8").replace("\r\n", "\n") if p.exists() else None
    stale = [p for p, text in outputs.items() if current(p) != text]
    if args.check:
        if stale:
            sys.exit("stale: " + ", ".join(str(p.relative_to(ROOT)) for p in stale))
        print("knuckles-army sites up to date")
        return
    for p in stale:
        p.write_text(outputs[p], encoding="utf-8", newline=eol[p])
    print("%d solid routines, %d reaction sites; wrote %d file(s)" % (len(callees), len(sites), len(stale)))


if __name__ == "__main__":
    main()
